const handoverActionTypes = {
  HAND_OVER_LOGIN_REQUEST: 'HAND_OVER_LOGIN_REQUEST',
  HAND_OVER_LOGIN_SUCCESS: 'HAND_OVER_LOGIN_SUCCESS',
  HAND_OVER_LOGIN_FAIL: 'HAND_OVER_LOGIN_FAIL',
  HAND_OVER_LOGIN_STATUS_CLEAR: 'HAND_OVER_LOGIN_STATUS_CLEAR',

  HANDOVER_INPUT: 'HANDOVER_INPUT',
  HANDOVER_INPUT_RESET: 'HANDOVER_INPUT_RESET',
};

export default handoverActionTypes;
