// export const SEND_GET_METER_REQUEST = 'SEND_GET_METER_REQUEST';

// export const FETCH_METER_FAIL = 'FETCH_METER_FAIL';

// export const FETCH_METER_SUCCESS = 'FETCH_METER_SUCCESS';

// export const CLEAN_METER_STATE = 'CLEAN_METER_STATE';

// export const SET_METER_DATA = 'SET_METER_DATA';
